### PR TITLE
Revisions 22, 23

### PR DESCRIPTION
**Pull request by jakobilobi**
- [Move branch validation workflow to correct path](https://github.com/dwellir-public/polkadot-operator/commit/b26ccd299f0cc12d70b78eec98497f13486199af)
- [Merge pull request](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/ec520878ff62368b9f59cadfd0d52df263bd56f9) https://github.com/dwellir-public/polkadot-operator/pull/44 [from dwellir-public/clarify-config-description](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/ec520878ff62368b9f59cadfd0d52df263bd56f9)
- [Removed the need for validator-address config param](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/42e20c262b76dcbe443c64af18360df90a90b565) https://github.com/dwellir-public/polkadot-operator/pull/46 https://github.com/dwellir-public/polkadot-operator/pull/41/commits/42e20c262b76dcbe443c64af18360df90a90b565
-[Merge pull request](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/1e73b41bbe43dc0ec7b0a04ef09b10e485c2a984) https://github.com/dwellir-public/polkadot-operator/pull/48 [from dwellir-public/liberland](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/1e73b41bbe43dc0ec7b0a04ef09b10e485c2a984)
- [Fixed typo in event result key for action](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/2e8e2d344bc31137a428811db48000424810bc41)
- [Merge pull request](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/3f2589345c13ecb6c20bbde141096393d1c678ea) https://github.com/dwellir-public/polkadot-operator/pull/49 [from dwellir-public/wasm_config](https://github.com/dwellir-public/polkadot-operator/pull/41/commits/3f2589345c13ecb6c20bbde141096393d1c678ea)

### CODE REVIEW

**Comment by jakobilobi** [comment]
[This PR](https://github.com/dwellir-public/polkadot-operator/pull/43) accidentally claimed rev 20, 21 -> this one becomes 22, 23.

**Comment by jakobilobi** [comment]
I think it is time to merge this for a new revision now. Two steps remain though:

- Anyone against releasing, e.g. some code just about to come in?
- We should do the standard tests with this code; deploy to this version, refresh from previous version to this one, use the actions in this one. Any taker to do that?

**Comment by jakobilobi** [comment]
Local tests of charm checks out. Someone please approve :D

**Review by Maharacha — APPROVED** [review]

**Comment by Maharacha** [comment]
Push to prod! :beers:

**Pull request merged**
