### PR TITLE
Small update to readme

### PR DESCRIPTION
**Pull request by jakobilobi**
When me and @jonathanudd deployed a node using this charm earlier today, we found some opportunity to make the readme clearer. Didn't know quite what the pipeline is for this new repo though.

Should we make a PR for any changes, or can smaller stuff still be merged straight to `origin/main`?

### CODE REVIEW

**Comment by Maharacha** [comment]
> When me and @jonathanudd deployed a node using this charm earlier today, we found some opportunity to make the readme clearer. Didn't know quite what the pipeline is for this new repo though.
> 
> Should we make a PR for any changes, or can smaller stuff still be merged straight to `origin/main`?

I think we can continue pushing directly for stuff that does not need someone else's attention. To reduce context switching for people.

**Review by Maharacha — APPROVED** [review]
Great that you did what Erik and I were too lazy to do when moving the repo! :D

**Comment by jakobilobi** [comment]
> I think we can continue pushing directly for stuff that does not need someone else's attention. To reduce context switching for people.

Sounds good :+1:

**Comment by jakobilobi** [comment]
The action launched by this merge failed: https://github.com/dwellir-public/polkadot-operator/actions/runs/5330890435

What should one do when that happens?

**Pull request merged**
