### PR TITLE
Revision 13

### PR DESCRIPTION
**Pull request by jonathanudd**
* Added support for running the chain asset-hub-rococo (https://github.com/dwellir-public/polkadot-operator/pull/26/commits/fad95fa28d5e6a619c76b2b63d7279d6c82015fe)
* Adapt to new layout of sha256 files of  https://github.com/paritytech/polkadot-sdk releases https://github.com/dwellir-public/polkadot-operator/pull/28
* Added link to docs https://github.com/dwellir-public/polkadot-operator/pull/27
* Check file size of sha256 file https://github.com/dwellir-public/polkadot-operator/pull/29

### CODE REVIEW

**Comment by erik78se** [comment]
> Waiting for #28, then I'd say we update revision.
> 
> Other opinions or agree? @erik78se @jonathanudd

agree

**Comment by erik78se** [comment]
I also say we should promote it to a "candidate" or even "stable" if we think we can follow our release-criterias somehow.

**Comment by erik78se** [comment]
I'm ok with either actually. I recognize that it might have to wait.

**Review by jakobilobi — APPROVED** [review]
Ready for lift off :rocket:

**Pull request merged**
